import { Audio } from "@remotion/media";
import { AbsoluteFill, Sequence, staticFile } from "remotion";
import { PM } from "./brand";
import { DashboardScene } from "./scenes/DashboardScene";
import { EndCardScene } from "./scenes/EndCardScene";
import { GlyphScene } from "./scenes/GlyphScene";
import { HeadlineScene } from "./scenes/HeadlineScene";
import { MarketsScene } from "./scenes/MarketsScene";
import { MarkScene } from "./scenes/MarkScene";
import { StepsScene } from "./scenes/StepsScene";
import { TileScene } from "./scenes/TileScene";
import { TradeScene } from "./scenes/TradeScene";
import { WordmarkScene } from "./scenes/WordmarkScene";
import { scene } from "./timeline";

/**
 * Polymate — 20 s brand film, 1920x1080 @ 30 fps.
 *
 * Three beats: (1) introduce the brand (shots 1–4), (2) show the product
 * (dashboard → markets → trade, shots 5–7), (3) how to start (shots 8–10).
 * Shots hard-cut on a 120 BPM grid like the reference reel; every cut and
 * cue comes from timeline.json, which also drives the generated audio.
 */
const SCENES: { id: string; Component: React.FC }[] = [
  { id: "mark", Component: MarkScene },
  { id: "glyph", Component: GlyphScene },
  { id: "tile", Component: TileScene },
  { id: "wordmark", Component: WordmarkScene },
  { id: "dashboard", Component: DashboardScene },
  { id: "markets", Component: MarketsScene },
  { id: "trade", Component: TradeScene },
  { id: "steps", Component: StepsScene },
  { id: "headline", Component: HeadlineScene },
  { id: "endcard", Component: EndCardScene },
];

export const Polymate: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: PM.cream }}>
      {SCENES.map(({ id, Component }) => {
        const s = scene(id);
        return (
          <Sequence
            key={id}
            name={id}
            from={s.start}
            durationInFrames={s.duration}
            premountFor={30}
          >
            <Component />
          </Sequence>
        );
      })}
      {/* Generated by scripts/polymate/generate_audio.py from timeline.json */}
      <Audio src={staticFile("polymate/audio/mix.wav")} />
    </AbsoluteFill>
  );
};
